; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = hw_v2_rev_a

[env]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
monitor_rts = 0
monitor_dtr = 0
monitor_speed = 115200

lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	h2zero/NimBLE-Arduino@^2.5.0
	santerilindfors/WiFiProvisioner@^2.0.0

[default_flags]
build_flags = 
	-D USE_EXT_ADV=1
	-D CONFIG_BT_NIMBLE_EXT_ADV=1
	-D USE_BT_CRYPTO=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-Wno-error=int-in-bool-context
	-Wno-error=overloaded-virtual
	-Wno-overloaded-virtual

[debug_flags]
build_flags = -D DEBUG_LOG

[release_flags]
build_flags = -O3

[env:hw_v1_rev_a]
build_flags = 
	-D HW_TARGET_V1_REV_A
	${default_flags.build_flags}
	${debug_flags.build_flags}

[env:hw_v2_rev_a]
build_flags = 
	-D HW_TARGET_V2_REV_A
	${default_flags.build_flags}
	${debug_flags.build_flags}
