; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = hw_v2_8pot_rev_a

[env]
platform = espressif32@6.13.0
board = esp32-c3-devkitc-02
framework = arduino, espidf
monitor_rts = 0
monitor_dtr = 0
monitor_speed = 115200
platform_packages =
    framework-espidf@3.50301.0
	platformio/toolchain-riscv32-esp@13.2.0+20240530
	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.0
lib_deps = h2zero/esp-nimble-cpp@2.5.0
; lib_deps = h2zero/NimBLE-Arduino@2.3.7
board_build.embed_txtfiles =
	managed_components\espressif__esp_insights\server_certs\https_server.crt
    managed_components\espressif__esp_rainmaker\server_certs\rmaker_mqtt_server.crt
    managed_components\espressif__esp_rainmaker\server_certs\rmaker_claim_service_server.crt
    managed_components\espressif__esp_rainmaker\server_certs\rmaker_ota_server.crt

[default_flags]
build_flags = 
	-D USE_EXT_ADV=1
	-D CONFIG_BT_NIMBLE_EXT_ADV=1
	-D USE_BT_CRYPTO=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-Wno-error=int-in-bool-context
	-Wno-error=overloaded-virtual
	-Wno-overloaded-virtual

[debug_flags]
build_flags = -D DEBUG_LOG

[release_flags]
build_flags = -O3

[env:hw_v1_1pot_rev_a]
build_flags = 
	-D HW_V1_1POT_REV_A
	${default_flags.build_flags}
	${debug_flags.build_flags}
board_build.sdkconfig_path = sdkconfig.hw_v1_1pot_rev_a

[env:hw_v2_8pot_rev_a]
build_flags = 
	-D HW_V2_8POT_REV_A
	${default_flags.build_flags}
	${debug_flags.build_flags}
board_build.sdkconfig_path = sdkconfig.hw_v2_8pot_rev_a

[env:hw_v2_8pot_rev_b]
build_flags = 
	-D HW_V2_8POT_REV_B
	${default_flags.build_flags}
	${debug_flags.build_flags}
board_build.sdkconfig_path = sdkconfig.hw_v2_8pot_rev_b